name: CI

on: [push, pull_request]

jobs:
  format:
    name: Validation of source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.0.1
          elixir-version: 1.17.2

      - name: Cache PLT files
        id: cache-plt
        uses: actions/cache@v2
        with:
          path: |
            _build/dev/*.plt
            _build/dev/*.plt.hash
            deps
          key: plt-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            plt-cache-

      - name: Validate
        run: mix do deps.get, validate

  test:
    name: Test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.18.x
            otp: 27
          - elixir: 1.18.x
            otp: 26
          - elixir: 1.18.x
            otp: 25
          - elixir: 1.17.x
            otp: 27
          - elixir: 1.17.x
            otp: 26
          - elixir: 1.17.x
            otp: 25
          - elixir: 1.16.x
            otp: 26
          - elixir: 1.15.x
            otp: 26
          - elixir: 1.14.x
            otp: 26
          - elixir: 1.14.x
            otp: 25
          - elixir: 1.13.x
            otp: 24
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Run tests
        run: mix test --trace
